### ISSUE TITLE
Updating for 2017.4

### ISSUE THREAD

**Issue by garengllc** [Xilinx/RFNoC-HLS-ATSC-RX#1]
Do you have updated instructions for installing on a system running the latest RFNoC code?  I'd like to give it a shot, but I am having issues getting it setup properly since they have changed paths and added in some patches.  Thanks!

**Comment by switchlanez** [comment]
Sorry, all RFNoC work I'm doing depends on 2015.4 and we haven't updated to
2017.4 yet. I suggest getting a basic HLS block built and working (like the
addsub example) then iteratively build the ATSC source the same way.

**Comment by garengllc** [comment]
OK, thanks for the quick feedback.  I haven't done HLS before, so it would have to be a back-burner project for me.  I'll report back if I do make any headway though.
